name: Bazel Build

on:
  push:
    tags:
      - "v**"

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        platform: ["macos-latest", "ubuntu-latest"]
        experimental: [false]
        include:
          - platform: windows-latest
            experimental: true
    steps:
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Cache Go Modules
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install Bazelisk
        if: matrix.platform != 'windows-latest'
        run: |
          go install github.com/bazelbuild/bazelisk@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          export USE_BAZEL_VERSION=8.3.0
          bazel version
        
      - name: Install Bazelisk on Windows
        if: matrix.platform == 'windows-latest'
        run: |
          go install github.com/bazelbuild/bazelisk@latest
          echo "$(go env GOPATH)\bin" >> $GITHUB_PATH
          setx USE_BAZEL_VERSION 8.3.0
          bazel version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Bazel
        if: matrix.platform != 'windows-latest'
        run: |
          bazel build //tetris:tetris --verbose_failures
          echo "binary_path=$(bazel info bazel-bin)/tetris" >> $GITHUB_ENV
      
      - name: Build with Bazel on Windows
        if: matrix.platform == 'windows-latest'
        run: |
          bazel build //tetris:tetris --verbose_failures
          echo "binary_path=$(bazel info bazel-bin)\tetris" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tetris-artifact-${{ matrix.platform }}
          path: |
            ${{ env.binary_path }}*
