name: Create Release

on:
  workflow_run:
    workflows: ["Bazel Build"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-slim
    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.workflow_run.head_branch }}
          name: ${{ github.event.workflow_run.head_branch }}
          body: "Automated release"
          artifacts: ./artifacts/**/*
          draft: false
          prerelease: false
